### ISSUE TITLE
Check completeness of new site

### ISSUE THREAD

**Issue by wolfgangmm** [HistoryAtState/hsg-shell#150] opened 2016-03-15 16:47 UTC
We need to make sure the new site has all the pages which were available on the old site. Can we create a crawler to collect all links on the new site, then run them against the new site? I did something like this in nodejs a while ago, but lost the code.

**Comment by line-o** [comment] 2016-03-23 11:55
We used to to that with `wget`, long ago.

**Comment by line-o** [comment] 2016-03-23 12:07
https://github.com/cgiffard/node-simplecrawler looks like a good start

**Comment by line-o** [comment] 2016-03-30 12:41
Finally, some results:
Missing pages are stored in 
[not-found.txt](https://github.com/eXistSolutions/hsg-shell/files/195492/not-found.txt)

**Comment by joewiz** [comment] 2016-03-30 13:59
To confirm, these are the results for the non-`/historicaldocuments/frus*` pages, correct?

**Comment by plutonik-a** [comment] 2016-03-30 14:00
Page `/open` is definitely not missing, at least I worked on it a minute ago on branch `fix-grid-layout` and it's linked from the main menu under "More Resources".

[http://localhost:8080/exist/apps/hsg-shell/open](http://localhost:8080/exist/apps/hsg-shell/open)
[https://history.state.gov/beta/open](https://history.state.gov/beta/open)

**Comment by joewiz** [comment] 2016-03-30 14:13
The /gallery result is expected, and /countries/issues is quite possible too.  But, like @plutonik-a's note about `/open`, I wonder about the `people` results. For example, one of the `not-found.txt` entries is found on the beta site: https://history.state.gov/beta/departmenthistory/people/ackerman-ralph-h (and I confirmed the response code is 200).  

@line-o Is it possible your hsg-shell (or hsg-project) is out of date?

**Comment by line-o** [comment] 2016-03-30 14:34
I rebuild data & database quite frequently. Last time was yesterday. But you are both right they are on the  beta site. Very strange.

**Comment by line-o** [comment] 2016-03-30 14:36
That is what happens on my machine:
<img width="518" alt="screen shot 2016-03-30 at 16 35 24" src="https://cloud.githubusercontent.com/assets/657222/14145795/79972f24-f695-11e5-8913-fb0e263a4515.png">

**Comment by line-o** [comment] 2016-03-30 14:40
I can now confirm my local version was outdated. Will re-run the tests!

**Comment by line-o** [comment] 2016-03-30 15:08
Here is the very short new list:
- /countries/issues
- /countries/issues/china-us-relations
- /countries/issues/german-unification
- /countries/issues/italian-unification
- /gallery
- /gallery/southeast-asia-conference
- /gallery/southeast-asia-conference?group=iconic
- /gallery/southeast-asia-conference?group=media
- /gallery/southeast-asia-conference?group=notable-people
- /gallery/southeast-asia-conference?group=on-the-ground
- /gallery/southeast-asia-conference?group=peace-negotiations
- /gallery/southeast-asia-conference?group=protest
- /historicaldocuments/guide-to-sources-on-vietnam-1969-1975

**Comment by plutonik-a** [comment] 2016-04-04 16:18
Ref: https://github.com/eXistSolutions/hsg-shell/issues/122

**Comment by joewiz** [comment] 2016-04-06 13:35
@plutonik-a Just curious, what is the relationship with #122?

**Comment by plutonik-a** [comment] 2016-04-06 13:40
That was most definitely an error, must have mixed up the urls of the issues.

**Comment by joewiz** [comment] 2016-04-06 14:37
Okay, no worries!

**Comment by line-o** [comment] 2016-05-26 16:14
Should we do a re-run and expect `/gallery` and `/countries/issues` now to be there as well?

**Comment by line-o** [comment] 2016-05-26 16:15
Otherwise we can close this issue and create a new one for those.

**Comment by joewiz** [comment] 2016-05-26 16:25
They're covered with existing issues: #97 for `/gallery` and #184 for `/countries/issues`.  Once those are complete, a re-run would be a great step to take before removing the "beta" label from the new site.

**Comment by joewiz** [comment] 2017-03-24 16:11
Closing this issue, since a full re-check of all site URLs is not necessary. The list above sufficed, and I've added those URLs to the relevant issues.

**Closed by joewiz** 2017-03-24 16:11 UTC
Labels: high priority
