### ISSUE TITLE
Tooltip over footnotes, sidebars is not displaying

### ISSUE THREAD

**Issue by joewiz** [HistoryAtState/hsg-shell#248] opened 2016-09-22 16:39 UTC
Hovering over footnotes such as those on https://history.state.gov/historicaldocuments/frus1977-80v16/d1 should display a styled tooltip with the text of the footnote. Hovering does nothing.

Likewise for the Persons and Terms & Abbreviations sidebar - except a plaintext tooltip appears. An image of the correct behavior is at https://github.com/HistoryAtState/hsg-shell/issues/140#issuecomment-194785368 (albeit a little out of date).

@plutonik-a Do you have any clues about this?

**Comment by joewiz** [comment] 2016-09-22 16:55
(cc @wolfgangmm.)

**Comment by joewiz** [comment] 2016-09-22 17:12
Found a better image showing the desired form, from https://github.com/HistoryAtState/hsg-shell/issues/238#issue-159922985:

<img width="299" alt="bildschirmfoto 2016-06-13 um 12 47 00" src="https://cloud.githubusercontent.com/assets/1157669/16004971/ff500960-3164-11e6-87c6-c4a7c7596870.png">

**Comment by joewiz** [comment] 2016-09-22 17:24
And here's how this looks to me on https://history.state.gov/historicaldocuments/frus1955-57v15/d159:

![screen shot 2016-09-22 at 1 23 42 pm](https://cloud.githubusercontent.com/assets/59118/18758877/e16586c0-80c7-11e6-9faf-cde73247586f.png)

**Comment by plutonik-a** [comment] 2016-09-22 18:01
Strange. Never saw that before...
I had a quick research if Bootstrap's `tooltip.scss`  
```
$tooltip-color: #fff !default;
$tooltip-bg:     #000 !default;
```
is overridden somewhere, but no hint so far.
I will fix this tomorrow then.

**Comment by joewiz** [comment] 2016-09-22 18:12
@plutonik-a Thank you!

**Comment by plutonik-a** [comment] 2016-09-23 15:18
I couldn't reproduce the bug on my machine with the current development code!
As I already pointed out in issue [247](https://github.com/HistoryAtState/hsg-shell/issues/247#issuecomment-249217836), there must be something else interfering in the live environment, that for some reason the styles are not rendered.

**Comment by joewiz** [comment] 2016-09-23 16:11
I just wiped and redeployed hsg-project on my development machine, and I'm not seeing the popup.  Can you confirm you see the popups even after wiping and redeploying on your machine?

**Comment by plutonik-a** [comment] 2016-09-23 19:02
> Can you confirm you see the popups even after wiping and redeploying on your machine?

Yes I can. Same here, I had to wipe and redeploy hsg-project, because my version was outdated.
After that I pulled the master branch from hsg-shell.
The screenshot above is the proof, that the pop-ups work fine on my local version.

**Comment by joewiz** [comment] 2016-09-23 19:50
I've gotten it to work on my machine, but I don't quite understand why yet. I noticed that when I ran `ant` on my command line (in the `hsg-shell`) directory, I was seeing `Production? true` even thought I had not set the NODE_ENV environmental variable to `production`. So I removed the line that passed the NODE_ENV variable to npm, line 15 of my local version of build.xml: https://github.com/HistoryAtState/hsg-shell/blob/master/build.xml#L15. 

Now when I run `ant`, I see `Production? false`, and the tooltips appear - both for sidebar entries and footnotes.

When I restore line 15, no matter what value I set NODE_ENV to, I always get `Production? true`. For example:

```bash
$ export NODE_ENV=blah
$ echo $NODE_ENV
blah
$ ant
...
     [echo] Production? true
```

And when the ant/npm process states that production is `true`, the tooltips do not work. 

Thus, it appears that something about the handling of the NODE_ENV variable is resulting in the failure of the tooltip code.

Does this shed any light on the situation?

**Comment by joewiz** [comment] 2016-10-03 23:57
Pardon my absence of javascript skills, but I traced the handling of this NODE_ENV environmental variable to https://github.com/HistoryAtState/hsg-shell/blob/master/gulpfile.js#L28, where we have this:

```js
var PRODUCTION = (!!process.env.NODE_ENV || process.env.NODE_ENV === 'production')
```

My understanding is that this will set PRODUCTION to true as long as the NODE_ENV environmental variable is set *at all*.  So if I set NODE_ENV to `blah`, PRODUCTION will still return `true`.  

Is this a clue?

**Comment by line-o** [comment] 2016-10-18 11:27
@joewiz it is not the cause of the issue but wrong nonetheless. You had to unset NODE_ENV to get the dev build.
fixed both in #254

**Comment by tuurma** [comment] 2017-03-22 21:13
I assume this is now fixed with @line-o's update to gulpfile and can be closed
@joewiz please reopen if necessary

**Comment by tuurma** [comment] 2017-03-22 21:14
![image](https://cloud.githubusercontent.com/assets/449468/24220995/73adc29e-0f44-11e7-972a-1241155cf937.png)

screenshot of current state of things for completeness

**Closed by tuurma** 2017-03-22 21:13 UTC
Labels: bug, CSS
